// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as GameOfLife from "./GameOfLife.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function App(props) {
  let match = React.useReducer(GameOfLife.reducer, GameOfLife.initial_state);
  let dispatch = match[1];
  let state = match[0];
  React.useEffect(() => {
    if (!state.running) {
      return;
    }
    let id = setInterval(() => dispatch("Step"), state.speed);
    return () => {
      clearInterval(id);
    };
  }, [
    state.running,
    state.speed
  ]);
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Conway's Game of Life",
        className: "text-4xl font-bold mb-8"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: state.running ? "Pause" : "Play",
            className: "px-6 py-2 bg-purple-600 hover:bg-purple-700 rounded-lg font-medium",
            onClick: param => dispatch("Toggle")
          }),
          JsxRuntime.jsx("button", {
            children: "Step",
            className: "px-6 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg font-medium",
            onClick: param => dispatch("Step")
          }),
          JsxRuntime.jsx("button", {
            children: "Clear",
            className: "px-6 py-2 bg-red-600 hover:bg-red-700 rounded-lg font-medium",
            onClick: param => dispatch("Clear")
          }),
          JsxRuntime.jsx("button", {
            children: "Randomize",
            className: "px-6 py-2 bg-green-600 hover:bg-green-700 rounded-lg font-medium",
            onClick: param => dispatch("Randomize")
          })
        ],
        className: "flex gap-4 mb-6"
      }),
      JsxRuntime.jsx("div", {
        children: "Grid rendering: TODO",
        className: "text-slate-400 text-sm"
      })
    ],
    className: "min-h-screen bg-slate-900 text-white flex flex-col items-center p-8"
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
