// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";
import * as GameOfLife from "./GameOfLife.res.mjs";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.js";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.js";
import * as Primitive_int from "@rescript/runtime/lib/es6/Primitive_int.js";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.js";
import * as JsxRuntime from "react/jsx-runtime";

function computeCellSize(cols) {
  let available = window.innerWidth - 32 | 0;
  let size = Primitive_int.div(available, cols);
  if (size > 15) {
    return 15;
  } else if (size < 8) {
    return 8;
  } else {
    return size;
  }
}

let storageKey = "gol:custom-presets";

function loadFromStorage() {
  let raw = localStorage.getItem(storageKey);
  if (raw == null) {
    return [];
  }
  let json;
  try {
    json = JSON.parse(raw);
  } catch (exn) {
    return [];
  }
  if (Array.isArray(json)) {
    return Stdlib_Array.filterMap(json, item => {
      if (typeof item !== "object" || item === null || Array.isArray(item)) {
        return;
      }
      let match = item["name"];
      let match$1 = item["cells"];
      if (typeof match === "string" && typeof match$1 === "string") {
        return {
          name: match,
          cells: match$1
        };
      }
    });
  } else {
    return [];
  }
}

function saveToStorage(presets) {
  let json = JSON.stringify(presets.map(p => ({
    name: p.name,
    cells: p.cells
  })));
  if (json !== undefined) {
    localStorage.setItem(storageKey, json);
    return;
  }
}

function App(props) {
  let match = React.useReducer(GameOfLife.reducer, GameOfLife.initial_state);
  let dispatch = match[1];
  let state = match[0];
  let match$1 = React.useState(() => computeCellSize(GameOfLife.cols));
  let setCellSize = match$1[1];
  let cellSize = match$1[0];
  let match$2 = React.useState(() => loadFromStorage());
  let setCustomPresets = match$2[1];
  let customPresets = match$2[0];
  let match$3 = React.useState(() => "");
  let setPresetName = match$3[1];
  let presetName = match$3[0];
  React.useEffect(() => {
    if (!state.running) {
      return;
    }
    let id = setInterval(() => dispatch("Step"), state.speed);
    return () => {
      clearInterval(id);
    };
  }, [
    state.running,
    state.speed
  ]);
  React.useEffect(() => {
    let handler = () => setCellSize(param => computeCellSize(GameOfLife.cols));
    window.addEventListener("resize", handler);
    return () => {
      window.removeEventListener("resize", handler);
    };
  }, []);
  React.useEffect(() => {
    let hash = window.location.hash();
    if (hash.length > 0) {
      let cleanHash = hash.slice(1);
      let match = GameOfLife.decode_url_state(cleanHash);
      if (match !== undefined) {
        dispatch({
          TAG: "LoadUrlState",
          _0: match[0],
          _1: match[1],
          _2: match[2]
        });
      }
    }
  }, []);
  let gridWidth = state.cols * cellSize | 0;
  let gridHeight = state.rows * cellSize | 0;
  let renderGrid = () => Stdlib_Array.fromInitializer(state.rows, r => JsxRuntime.jsx("div", {
    children: Stdlib_Array.fromInitializer(state.cols, c => {
      let age = GameOfLife.get_age(state.ages, state.cols, r, c);
      let color = GameOfLife.compute_age_color(age);
      return JsxRuntime.jsx("div", {
        className: "cursor-pointer",
        style: {
          backgroundColor: color,
          height: cellSize.toString() + "px",
          width: cellSize.toString() + "px"
        },
        onClick: param => dispatch({
          TAG: "ToggleCell",
          _0: r,
          _1: c
        })
      }, c.toString());
    }),
    className: "flex"
  }, r.toString()));
  let liveCount = GameOfLife.count_alive(state.grid);
  let maxAge = Stdlib_Array.reduce(state.ages, 0, (acc, age) => {
    if (age > acc) {
      return age;
    } else {
      return acc;
    }
  });
  let ruleLabel = Primitive_object.equal(state.rule, GameOfLife.conway) ? "Conway (B3/S23)" : (
      Primitive_object.equal(state.rule, GameOfLife.highlife) ? "HighLife (B36/S23)" : (
          Primitive_object.equal(state.rule, GameOfLife.maze) ? "Maze (B3/S12345)" : (
              Primitive_object.equal(state.rule, GameOfLife.dayAndNight) ? "Day & Night (B3678/S34678)" : "Custom"
            )
        )
    );
  let handleSpeedChange = e => {
    let value = e.target.value;
    let speed = Stdlib_Int.fromString(value, undefined);
    if (speed !== undefined) {
      return dispatch({
        TAG: "SetSpeed",
        _0: 600 - (speed * 5 | 0) | 0
      });
    }
  };
  return JsxRuntime.jsxs("div", {
    children: [
      JsxRuntime.jsx("h1", {
        children: "Conway's Game of Life",
        className: "text-2xl md:text-4xl font-bold mb-4 md:mb-8"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: state.running ? "Pause" : "Play",
            className: "px-4 py-2 bg-purple-600 hover:bg-purple-700 rounded-lg font-medium",
            onClick: param => dispatch("Toggle")
          }),
          JsxRuntime.jsx("button", {
            children: "Step",
            className: "px-4 py-2 bg-blue-600 hover:bg-blue-700 rounded-lg font-medium",
            onClick: param => dispatch("Step")
          }),
          JsxRuntime.jsx("button", {
            children: "Clear",
            className: "px-4 py-2 bg-red-600 hover:bg-red-700 rounded-lg font-medium",
            onClick: param => dispatch("Clear")
          }),
          JsxRuntime.jsx("button", {
            children: "Randomize",
            className: "px-4 py-2 bg-green-600 hover:bg-green-700 rounded-lg font-medium",
            onClick: param => dispatch("Randomize")
          }),
          JsxRuntime.jsx("button", {
            children: "Share",
            className: "px-4 py-2 bg-indigo-600 hover:bg-indigo-700 rounded-lg font-medium",
            onClick: param => {
              window.location.hash("#" + GameOfLife.encode_url_state(state.grid, state.rows, state.cols));
            }
          })
        ],
        className: "flex flex-wrap gap-2 mb-4 justify-center"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Glider",
            className: "px-3 py-1 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-sm",
            onClick: param => dispatch({
              TAG: "LoadPreset",
              _0: "Glider"
            })
          }),
          JsxRuntime.jsx("button", {
            children: "Blinker",
            className: "px-3 py-1 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-sm",
            onClick: param => dispatch({
              TAG: "LoadPreset",
              _0: "Blinker"
            })
          }),
          JsxRuntime.jsx("button", {
            children: "Pulsar",
            className: "px-3 py-1 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-sm",
            onClick: param => dispatch({
              TAG: "LoadPreset",
              _0: "Pulsar"
            })
          }),
          JsxRuntime.jsx("button", {
            children: "R-Pentomino",
            className: "px-3 py-1 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-sm",
            onClick: param => dispatch({
              TAG: "LoadPreset",
              _0: "RPentomino"
            })
          })
        ],
        className: "flex flex-wrap gap-2 mb-4 justify-center"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("button", {
            children: "Conway",
            className: Primitive_object.equal(state.rule, GameOfLife.conway) ? "px-3 py-1 bg-purple-700 hover:bg-purple-600 rounded-lg font-medium text-sm" : "px-3 py-1 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-sm",
            onClick: param => dispatch({
              TAG: "SetRule",
              _0: GameOfLife.conway
            })
          }),
          JsxRuntime.jsx("button", {
            children: "HighLife",
            className: Primitive_object.equal(state.rule, GameOfLife.highlife) ? "px-3 py-1 bg-purple-700 hover:bg-purple-600 rounded-lg font-medium text-sm" : "px-3 py-1 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-sm",
            onClick: param => dispatch({
              TAG: "SetRule",
              _0: GameOfLife.highlife
            })
          }),
          JsxRuntime.jsx("button", {
            children: "Maze",
            className: Primitive_object.equal(state.rule, GameOfLife.maze) ? "px-3 py-1 bg-purple-700 hover:bg-purple-600 rounded-lg font-medium text-sm" : "px-3 py-1 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-sm",
            onClick: param => dispatch({
              TAG: "SetRule",
              _0: GameOfLife.maze
            })
          }),
          JsxRuntime.jsx("button", {
            children: "Day & Night",
            className: Primitive_object.equal(state.rule, GameOfLife.dayAndNight) ? "px-3 py-1 bg-purple-700 hover:bg-purple-600 rounded-lg font-medium text-sm" : "px-3 py-1 bg-slate-600 hover:bg-slate-500 rounded-lg font-medium text-sm",
            onClick: param => dispatch({
              TAG: "SetRule",
              _0: GameOfLife.dayAndNight
            })
          })
        ],
        className: "flex flex-wrap gap-2 mb-4 justify-center"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("span", {
            children: "Gen: " + state.generation.toString(),
            className: "text-slate-400"
          }),
          JsxRuntime.jsx("span", {
            children: "Live: " + liveCount.toString(),
            className: "text-slate-400"
          }),
          JsxRuntime.jsx("span", {
            children: "Max Age: " + maxAge.toString(),
            className: "text-slate-400"
          }),
          JsxRuntime.jsx("span", {
            children: "Rule: " + ruleLabel,
            className: "text-slate-400"
          })
        ],
        className: "flex gap-6 mb-3 text-sm font-mono"
      }),
      JsxRuntime.jsxs("div", {
        children: [
          JsxRuntime.jsx("div", {
            children: renderGrid(),
            className: "border border-slate-700",
            style: {
              height: gridHeight.toString() + "px",
              width: gridWidth.toString() + "px"
            }
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("label", {
                children: "Speed:",
                className: "text-sm text-slate-400 whitespace-nowrap",
                htmlFor: "speed-slider"
              }),
              JsxRuntime.jsx("input", {
                defaultValue: "60",
                className: "flex-1 h-2 bg-slate-700 rounded-lg appearance-none cursor-pointer",
                id: "speed-slider",
                max: "120",
                min: "0",
                type: "range",
                onChange: handleSpeedChange
              })
            ],
            className: "flex items-center gap-2 w-full max-w-xs"
          }),
          JsxRuntime.jsxs("div", {
            children: [
              JsxRuntime.jsx("input", {
                className: "px-3 py-1 bg-slate-700 rounded-lg text-sm text-white border border-slate-600 focus:outline-none",
                placeholder: "Preset name...",
                type: "text",
                value: presetName,
                onChange: e => setPresetName(param => e.target.value)
              }),
              JsxRuntime.jsx("button", {
                children: "Save Preset",
                className: "px-3 py-1 bg-yellow-600 hover:bg-yellow-500 rounded-lg font-medium text-sm",
                onClick: param => {
                  let trimmed = presetName.trim();
                  if (!(trimmed.length > 0 && !customPresets.some(p => p.name === trimmed))) {
                    return;
                  }
                  let newPreset_cells = GameOfLife.serialize_grid(state.grid);
                  let newPreset = {
                    name: trimmed,
                    cells: newPreset_cells
                  };
                  let updated = customPresets.concat([newPreset]);
                  setCustomPresets(param => updated);
                  saveToStorage(updated);
                  setPresetName(param => "");
                }
              })
            ],
            className: "flex flex-wrap gap-2 mt-4 justify-center items-center"
          }),
          customPresets.length !== 0 ? JsxRuntime.jsx("div", {
              children: customPresets.map(p => JsxRuntime.jsxs("div", {
                children: [
                  JsxRuntime.jsx("button", {
                    children: p.name,
                    className: "px-3 py-1 bg-teal-700 hover:bg-teal-600 rounded-lg font-medium text-sm",
                    onClick: param => {
                      let cells = GameOfLife.deserialize_grid(p.cells);
                      dispatch({
                        TAG: "LoadCustomPreset",
                        _0: cells
                      });
                    }
                  }),
                  JsxRuntime.jsx("button", {
                    children: "×",
                    className: "px-2 py-1 bg-slate-700 hover:bg-red-700 rounded text-xs",
                    onClick: param => {
                      let updated = customPresets.filter(q => q.name !== p.name);
                      setCustomPresets(param => updated);
                      saveToStorage(updated);
                    }
                  })
                ],
                className: "flex items-center gap-1"
              }, p.name)),
              className: "flex flex-wrap gap-2 mt-2 justify-center"
            }) : null
        ],
        className: "flex flex-col items-center gap-4 mb-6"
      })
    ],
    className: "min-h-screen bg-slate-900 text-white flex flex-col items-center p-3 md:p-8"
  });
}

let make = App;

export {
  make,
}
/* react Not a pure module */
