// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "react/jsx-runtime";

function Button(props) {
  let onClick = props.onClick;
  return JsxRuntime.jsx("button", {
    children: props.label,
    className: "px-6 py-2 bg-purple-600 hover:bg-purple-700 rounded-lg font-medium transition-colors",
    onClick: param => onClick()
  });
}

let make = Button;

export {
  make,
}
/* react/jsx-runtime Not a pure module */
