// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.res.mjs";
import * as JsxRuntime from "react/jsx-runtime";

function Main(props) {
  return JsxRuntime.jsx(App.make, {});
}

let make = Main;

export {
  make,
}
/* App Not a pure module */
