// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Vitest from "rescript-vitest/src/Vitest.res.mjs";
import * as GameOfLife from "../src/GameOfLife.res.mjs";

Vitest.describe("make_grid", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("creates grid with correct total size (rows * cols)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(3, 4);
    t.expect(grid.length).toBe(12);
  });
  Vitest.test("all cells initialized to Dead", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    t.expect(GameOfLife.count_alive(grid)).toBe(0);
  });
});

Vitest.describe("get_cell and set_cell", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("set then get returns Alive", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 3, "Alive");
    t.expect(GameOfLife.get_cell(grid, 5, 2, 3)).toBe("Alive");
  });
  Vitest.test("unset cell returns Dead", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    t.expect(GameOfLife.get_cell(grid, 5, 1, 1)).toBe("Dead");
  });
  Vitest.test("out-of-bounds get returns Dead (not a crash)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    t.expect(GameOfLife.get_cell(grid, 5, 10, 10)).toBe("Dead");
  });
  Vitest.test("negative row index returns Dead", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    t.expect(GameOfLife.get_cell(grid, 5, -1, 0)).toBe("Dead");
  });
  Vitest.test("set overwrites an existing value", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 2, "Dead");
    t.expect(GameOfLife.get_cell(grid, 5, 2, 2)).toBe("Dead");
  });
});

Vitest.describe("count_live_neighbors — finite boundary", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("isolated cell has 0 neighbors", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 2, 2)).toBe(0);
  });
  Vitest.test("counts all 8 surrounding neighbors", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 1, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 3, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 3, "Alive");
    GameOfLife.set_cell(grid, 5, 3, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 3, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 3, 3, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 2, 2)).toBe(8);
  });
  Vitest.test("cell itself is not counted as its own neighbor", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 2, 2)).toBe(0);
  });
  Vitest.test("top-left corner has at most 3 in-bounds neighbors", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 0, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 0, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 1, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 0, 0)).toBe(3);
  });
  Vitest.test("top edge cell counts only in-bounds neighbors", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 0, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 0, 3, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 3, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 0, 2)).toBe(5);
  });
  Vitest.test("bottom-right corner has at most 3 in-bounds neighbors", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 3, 3, "Alive");
    GameOfLife.set_cell(grid, 5, 3, 4, "Alive");
    GameOfLife.set_cell(grid, 5, 4, 3, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 4, 4)).toBe(3);
  });
});

Vitest.describe("compute_next_gen — Conway's rules", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("underpopulation: live cell with 0 neighbors dies", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.get_cell(next, 5, 2, 2)).toBe("Dead");
  });
  Vitest.test("underpopulation: live cell with 1 neighbor dies", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 3, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.get_cell(next, 5, 2, 2)).toBe("Dead");
  });
  Vitest.test("survival: live cell with 2 neighbors survives", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 3, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.get_cell(next, 5, 2, 2)).toBe("Alive");
  });
  Vitest.test("survival: live cell with 3 neighbors survives", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 3, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.get_cell(next, 5, 2, 2)).toBe("Alive");
  });
  Vitest.test("overpopulation: live cell with 4 neighbors dies", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 1, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 3, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 3, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.get_cell(next, 5, 2, 2)).toBe("Dead");
  });
  Vitest.test("reproduction: dead cell with exactly 3 neighbors becomes alive", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 3, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.get_cell(next, 5, 1, 2)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 5, 3, 2)).toBe("Alive");
  });
  Vitest.test("dead cell with 2 neighbors stays dead", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 3, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.get_cell(next, 5, 2, 1)).toBe("Dead");
  });
  Vitest.test("dead cell with 4 neighbors stays dead", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 1, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 3, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 1, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 3, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.get_cell(next, 5, 2, 2)).toBe("Dead");
  });
  Vitest.test("blinker oscillates: horizontal → vertical → horizontal", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(7, 7);
    GameOfLife.set_cell(grid, 7, 3, 2, "Alive");
    GameOfLife.set_cell(grid, 7, 3, 3, "Alive");
    GameOfLife.set_cell(grid, 7, 3, 4, "Alive");
    let gen1 = GameOfLife.compute_next_gen(grid, 7, 7);
    t.expect(GameOfLife.get_cell(gen1, 7, 2, 3)).toBe("Alive");
    t.expect(GameOfLife.get_cell(gen1, 7, 3, 3)).toBe("Alive");
    t.expect(GameOfLife.get_cell(gen1, 7, 4, 3)).toBe("Alive");
    t.expect(GameOfLife.get_cell(gen1, 7, 3, 2)).toBe("Dead");
    t.expect(GameOfLife.get_cell(gen1, 7, 3, 4)).toBe("Dead");
    let gen2 = GameOfLife.compute_next_gen(gen1, 7, 7);
    t.expect(GameOfLife.get_cell(gen2, 7, 3, 2)).toBe("Alive");
    t.expect(GameOfLife.get_cell(gen2, 7, 3, 3)).toBe("Alive");
    t.expect(GameOfLife.get_cell(gen2, 7, 3, 4)).toBe("Alive");
    t.expect(GameOfLife.get_cell(gen2, 7, 2, 3)).toBe("Dead");
    t.expect(GameOfLife.get_cell(gen2, 7, 4, 3)).toBe("Dead");
  });
  Vitest.test("block (2x2) is a still life — never changes", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(6, 6);
    GameOfLife.set_cell(grid, 6, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 6, 2, 3, "Alive");
    GameOfLife.set_cell(grid, 6, 3, 2, "Alive");
    GameOfLife.set_cell(grid, 6, 3, 3, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 6, 6);
    t.expect(GameOfLife.count_alive(next)).toBe(4);
    t.expect(GameOfLife.get_cell(next, 6, 2, 2)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 6, 2, 3)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 6, 3, 2)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 6, 3, 3)).toBe("Alive");
  });
  Vitest.test("empty grid stays empty", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    let next = GameOfLife.compute_next_gen(grid, 5, 5);
    t.expect(GameOfLife.count_alive(next)).toBe(0);
  });
});

Vitest.describe("count_alive", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("empty grid returns 0", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    t.expect(GameOfLife.count_alive(grid)).toBe(0);
  });
  Vitest.test("counts 3 live cells correctly", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 0, 0, "Alive");
    GameOfLife.set_cell(grid, 5, 2, 2, "Alive");
    GameOfLife.set_cell(grid, 5, 4, 4, "Alive");
    t.expect(GameOfLife.count_alive(grid)).toBe(3);
  });
  Vitest.test("full 3x3 grid counts 9", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(3, 3);
    let r = 0;
    while (r < 3) {
      let c = 0;
      while (c < 3) {
        GameOfLife.set_cell(grid, 3, r, c, "Alive");
        c = c + 1 | 0;
      };
      r = r + 1 | 0;
    };
    t.expect(GameOfLife.count_alive(grid)).toBe(9);
  });
});

Vitest.describe("count_live_neighbors — toroidal wrap-around", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("top-left corner (0,0) wraps to see bottom-right corner (rows-1, cols-1)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 4, 4, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 0, 0)).toBe(1);
  });
  Vitest.test("top row wraps to see bottom row as neighbor", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 4, 2, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 0, 2)).toBe(1);
  });
  Vitest.test("bottom row wraps to see top row as neighbor", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 0, 2, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 4, 2)).toBe(1);
  });
  Vitest.test("left column wraps to see right column as neighbor", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 4, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 2, 0)).toBe(1);
  });
  Vitest.test("right column wraps to see left column as neighbor", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    GameOfLife.set_cell(grid, 5, 2, 0, "Alive");
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 2, 4)).toBe(1);
  });
  Vitest.test("corner cell always has exactly 8 neighbors (toroidal, not 3 like finite)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    let r = 0;
    while (r < 5) {
      let c = 0;
      while (c < 5) {
        if (r !== 0 || c !== 0) {
          GameOfLife.set_cell(grid, 5, r, c, "Alive");
        }
        c = c + 1 | 0;
      };
      r = r + 1 | 0;
    };
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 0, 0)).toBe(8);
  });
  Vitest.test("edge cell always has exactly 8 neighbors (toroidal, not 5 like finite)", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(5, 5);
    let r = 0;
    while (r < 5) {
      let c = 0;
      while (c < 5) {
        if (r !== 0 || c !== 2) {
          GameOfLife.set_cell(grid, 5, r, c, "Alive");
        }
        c = c + 1 | 0;
      };
      r = r + 1 | 0;
    };
    t.expect(GameOfLife.count_live_neighbors(grid, 5, 5, 0, 2)).toBe(8);
  });
});

Vitest.describe("compute_next_gen — toroidal wrap-around", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, () => {
  Vitest.test("blinker at bottom edge wraps: vertical arm appears at top row", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(7, 7);
    GameOfLife.set_cell(grid, 7, 6, 2, "Alive");
    GameOfLife.set_cell(grid, 7, 6, 3, "Alive");
    GameOfLife.set_cell(grid, 7, 6, 4, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 7, 7);
    t.expect(GameOfLife.get_cell(next, 7, 5, 3)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 7, 6, 3)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 7, 0, 3)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 7, 6, 2)).toBe("Dead");
    t.expect(GameOfLife.get_cell(next, 7, 6, 4)).toBe("Dead");
  });
  Vitest.test("blinker at right edge wraps: vertical arm appears at left column", undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, t => {
    let grid = GameOfLife.make_grid(7, 7);
    GameOfLife.set_cell(grid, 7, 2, 6, "Alive");
    GameOfLife.set_cell(grid, 7, 3, 6, "Alive");
    GameOfLife.set_cell(grid, 7, 4, 6, "Alive");
    let next = GameOfLife.compute_next_gen(grid, 7, 7);
    t.expect(GameOfLife.get_cell(next, 7, 3, 5)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 7, 3, 6)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 7, 3, 0)).toBe("Alive");
    t.expect(GameOfLife.get_cell(next, 7, 2, 6)).toBe("Dead");
    t.expect(GameOfLife.get_cell(next, 7, 4, 6)).toBe("Dead");
  });
});

/*  Not a pure module */
